
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4']
    steps:
      - uses: actions/checkout@v1
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, gd, zip
          ini-values: max_execution_time=600, memory_limit=-1
          coverage: xdebug
      - name: Create env file
        run: |
          cp .env.test .env
          cat .env
      - name: Validate composer.json
        run: |
          curl -sS https://getcomposer.org/installer | php -- --filename=composer
          composer validate
      - name: Install dependency
        run: |
          composer install
      - name: Run Unit tests
        run: |
          composer unit
      - name: Run Botman tests
        run: |
          composer botman-tests